version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "sdarq-frontend"
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "4200:4200"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "sdarq-backend"
    volumes:
        - ./backend:/app
    ports:
      - "5000:5000"